# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d1b5ff6eefe8f302978f00c81f840cfe39823f26d2cda903d6b1f312d0aaf1bff97b0f6d517138eaa2666a6b691453de37688602a29dff14717ba93bbc7dd01

test:
  secret_key_base: 25d33c5be490197eac6399c613cced2446d4f77f95906c33dc3d1daff666af6c84c1ee2308b51f6cda0c7dd8f1e9a37f94efc3b977dda4804a7a1f03a9272ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
